DB_SOURCE_SS="98.87.127.66"
DB_DATABASE_SS="salessystem"
DB_USERNAME_SS="admindb"
DB_TOKEN_SS="Giu72656770"
DB_PORT_SS='13306'
DB_SOURCE_WH="98.87.127.66"
DB_DATABASE_WH="warehouse"
DB_USERNAME_WH="admindb"
DB_TOKEN_WH="Giu72656770"
DB_PORT_WH='15432'