DB_SOURCE_SS="sales-system.c988owwqmmkd.us-east-1.rds.amazonaws.com"
DB_DATABASE_SS="salessystem"
DB_USERNAME_SS="admin"
DB_TOKEN_SS="Giu72656770"
DB_SOURCE_WH="datawarehouse.cgvmexzrrsgs.us-east-1.rds.amazonaws.coms"
DB_DATABASE_WH="warehouse"
DB_USERNAME_WH="admindb"
DB_TOKEN_WH="72656770"